version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"

  dotnet:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      - dotnetapp:/app
    working_dir: /app
    #command: bash -c "dotnet restore && dotnet build && dotnet sign --certificate path/to/certificate.pfx --password $CERT_PASSWORD --assembly path/to/assembly.dll"

  artifact-uploader:
    image: appropriate/curl
    volumes:
      - dotnetapp:/app
    working_dir: /app
    #command: bash -c "curl -X POST -F 'data=@/app/myartifact.zip' http://api-endpoint/upload"

volumes:
  jenkins_home:
  dotnetapp:
